# Development Docker Compose with hot reloading
version: '3.8'

services:
  # Development app with hot reloading
  bakery-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=development
      - REACT_APP_API_BASE_URL=http://localhost:3002
      - REACT_APP_REVOLUT_API_URL=https://sandbox-merchant.revolut.com
      - REACT_APP_ENVIRONMENT=development
      - REACT_APP_EMAIL_SERVER_URL=http://localhost:3001
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./package.json:/app/package.json
      - /app/node_modules
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - bakery-dev-network
    depends_on:
      - email-server
      - secure-api

  # Secure API server with JWT authentication and security features
  secure-api:
    build:
      context: ./api-server
      dockerfile: Dockerfile
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
      - PORT=3002
      - JWT_SECRET=TortoManiya-Super-Secure-JWT-Secret-2024-Change-This-In-Production-12345
      - JWT_EXPIRES_IN=7d
      - BCRYPT_SALT_ROUNDS=12
      - SESSION_SECRET=TortoManiya-Super-Secure-Session-Secret-2024-Change-This-In-Production-67890
      - DB_PATH=/app/data/bakery.db
      - LOG_LEVEL=info
      - CORS_ORIGIN=http://localhost:4000
    volumes:
      - api-data:/app/data
      - api-logs:/app/logs
    restart: unless-stopped
    networks:
      - bakery-dev-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Email server for sending emails via Gmail SMTP
  email-server:
    build:
      context: ./email-server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - EMAIL_SERVER_PORT=3001
      - GMAIL_USER=aopopov01@gmail.com
      - GMAIL_APP_PASSWORD=oydm ftxq jnkb zskk
    volumes:
      - ./email-templates:/app/email-templates:ro
      - ./email-server/logs:/app/logs
    restart: unless-stopped
    networks:
      - bakery-dev-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  api-data:
    driver: local
  api-logs:
    driver: local

networks:
  bakery-dev-network:
    driver: bridge